next-version: 1.7.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch

branches:
  master:
    regex: ^master$
    mode: ContinuousDelivery
    increment: Patch
    tag: ''
    is-release-branch: true
