next-version: 1.0
assembly-versioning-scheme: MajorMinor
assembly-file-versioning-scheme: MajorMinor
mode: ContinuousDeployment

branches:
  master:
    regex: ^master$
    increment: Minor
    tag: ''
    is-release-branch: true
