next-version: 1.0
assembly-versioning-scheme: MajorMinor
assembly-file-versioning-scheme: MajorMinor

branches:
  master:
    regex: ^master$
    mode: ContinuousDelivery
    increment: Minor
    tag: ''
    is-release-branch: true
